[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "geodata_calibration"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = ["src/geodata_calibration"]
      
[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]